### PR TITLE
Fix #211: Append System.lineSeparator() to last line

### LINKED ISSUE #211: Aggregation does not behave correctly when input files end with a comment
When using an aggregation, the input files are concatenated with a semicolon separating them. While this works in most cases, it fails when an input file ends with a comment (like a source map url). In this case, the first line of the next input file will also be commented out which can result in compilation failures.

### reproducer

1-file.js
```js
//# sourceMappingURL=1-file.js.map;
```

2-file.js
```js
/*
 * Hello World!
 */
```

aggregation.source.js
```js
//# sourceMappingURL=1-file.js.map;;/*
 * Hello World!
 */
```

Error message
```
Resources optimization failure: Illegal char <*> at index 16: 1-file.js.map;;/*
```

[reproducer.zip](https://github.com/user-attachments/files/17202571/reproducer.zip)

### PR DESCRIPTION
**Pull request by melloware**
Fix #211: Append System.lineSeparator() to last line

### CODE REVIEW

File: src/main/java/org/primefaces/extensions/optimizerplugin/optimizer/AbstractOptimizer.java [hunk 1]
```diff
@@ -93,19 +93,19 @@ protected File aggregateFiles(ResourcesSetAdapter rsa, Charset cset, boolean del
 
                 if (delimeters && outputFile.length() > 0) {
                     // append semicolon to the new file in order to avoid invalid JS code
-                    Files.asCharSink(outputFile, cset, FileWriteMode.APPEND).write(";");
+                    Files.asCharSink(outputFile, cset, FileWriteMode.APPEND).write(System.lineSeparator() + ";");
                 }
 
                 // write / append content into / to the new file
-                Files.asCharSink(outputFile, cset, FileWriteMode.APPEND).write(writer.toString());
+                Files.asCharSink(outputFile, cset, FileWriteMode.APPEND).write(System.lineSeparator() + writer.toString());
```
Comment (blutorange) [inline src/main/java/org/primefaces/extensions/optimizerplugin/optimizer/AbstractOptimizer.java:100]: Looks all good to me :+1:  Technically I suppose this adds two line terminators to JS files (?), but there's no problem with that. Regarding the type of line separator, both CSS and EcmaScript support both `\n\r` and `\n`, so that should also be ok.

A micro-optimization (probably not needed): Call `write` twice instead of concatenating `System.lineSeparator()` with `writer.toString()`.

Comment (melloware) [reply src/main/java/org/primefaces/extensions/optimizerplugin/optimizer/AbstractOptimizer.java]: good idea just refactored to make it cleaner
